from distutils.core import setup
setup(name='solidpinball',
      version='2014.10.15',
      license='GNU GPLv3+',
      packages=['pinball', 'pinball.parts'],
      description='A digital fabrication framework for pinball machines using Python',
      author='Felipe Correa da Silva Sanches',
      author_email='juca@members.fsf.org',
      url='https://github.com/felipesanches/SolidPinball/',
      download_url = 'https://github.com/felipesanches/SolidPinball/releases/tag/0.2014.10.15',
      install_requires=['solidpython'],
      classifiers=[
        "Programming Language :: Python",
        "Development Status :: 4 - Beta",
        "Topic :: Multimedia :: Graphics :: 3D Modeling",
        "Topic :: Games/Entertainment :: Arcade",
        "Intended Audience :: Manufacturing",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Libraries :: Python Modules",
      ],
      )
